name: start
version: 0.1.1
authors:
- Yehor Lvivski <lvivski@gmail.com>
- Collin Bell <cbell39@utk.edu>
description: Sinatra inspired Web framework
homepage: https://github.com/lvivski/start
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
  unittest: '>=0.2.7'
